"use client";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabaseClient";

export default function IndicatorsDashboard() {
  const [data,setData]=useState({products:[],issues:[],tasks:[],budgets:[]});
  useEffect(()=>{Promise.all([supabase.from("products").select("id,status"),supabase.from("product_issues").select("id,priority,due_date").is("resolved_at",null),supabase.from("product_development_tasks").select("id,status"),supabase.from("product_budget_items").select("id,currency,amount,quantity,mkp,overhead_rate,approved")]).then(([p,i,t,b])=>setData({products:p.data??[],issues:i.data??[],tasks:t.data??[],budgets:b.data??[]}));},[]);
  const k=useMemo(()=>{const done=data.tasks.filter(t=>t.status==="completed").length;const blocked=data.tasks.filter(t=>t.status==="blocked").length;const brl=data.budgets.filter(b=>b.currency==="BRL").reduce((s,b)=>s+Number(b.amount)*Number(b.quantity)*Number(b.mkp)*(1+Number(b.overhead_rate)/100),0);const usd=data.budgets.filter(b=>b.currency==="USD").reduce((s,b)=>s+Number(b.amount)*Number(b.quantity)*Number(b.mkp)*(1+Number(b.overhead_rate)/100),0);return{done,blocked,taskRate:data.tasks.length?Math.round(done/data.tasks.length*100):0,critical:data.issues.filter(i=>i.priority==="critica").length,approved:data.budgets.filter(b=>b.approved).length,brl,usd};},[data]);
  return <main className="analytics-page"><section className="analytics-hero"><span>Inteligência operacional</span><h1>Indicadores</h1><p>Transforme o andamento do portfólio em sinais claros para decisões rápidas.</p></section><section className="analytics-kpis"><article><small>Produtos monitorados</small><strong>{data.products.length}</strong><i style={{"--value":`${Math.min(data.products.length*8,100)}%`}}/></article><article className="danger"><small>Pendências críticas</small><strong>{k.critical}</strong><i style={{"--value":`${Math.min(k.critical*15,100)}%`}}/></article><article className="success"><small>Execução do desenvolvimento</small><strong>{k.taskRate}%</strong><i style={{"--value":`${k.taskRate}%`}}/></article><article><small>Orçamentos aprovados</small><strong>{k.approved}</strong><i style={{"--value":`${Math.min(k.approved*10,100)}%`}}/></article></section><section className="analytics-grid"><article className="analytics-panel"><header><span>Fluxo de desenvolvimento</span><strong>{k.done}/{data.tasks.length}</strong></header><div className="big-progress"><i style={{width:`${k.taskRate}%`}}/></div><div className="indicator-split"><span><b className="green-dot"/>Concluídas <strong>{k.done}</strong></span><span><b className="red-dot"/>Bloqueadas <strong>{k.blocked}</strong></span><span><b className="gray-dot"/>Em aberto <strong>{data.tasks.length-k.done}</strong></span></div></article><article className="analytics-panel finance"><header><span>Orçamento consolidado</span></header><div><span><small>BRL</small><strong>{k.brl.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</strong></span><span><small>USD</small><strong>{k.usd.toLocaleString("en-US",{style:"currency",currency:"USD"})}</strong></span></div><p>Moedas apresentadas separadamente, sem conversão cambial.</p></article></section></main>;
}
