"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabaseClient";

const blank={application:"",compatibility:"",annual_sales:"",stock_quantity:"",minimum_stock:"",unit_cost:"",sale_price:"",lead_time_days:"",supplier_name:"",supplier_country:"",certification_status:"not_required",certification_expiry:"",competitor_name:"",competitor_price:"",lifecycle_status:"active",single_source:false,known_risks:"",strategic_notes:""};
const numeric=["annual_sales","stock_quantity","minimum_stock","unit_cost","sale_price","lead_time_days","competitor_price"];

export default function StrategicIntelligenceDashboard({onOpenProduct}){
  const [db,setDb]=useState({products:[],profiles:[],bom:[],issues:[]});
  const [selectedId,setSelectedId]=useState("");const[form,setForm]=useState(blank);const[message,setMessage]=useState("");const[saving,setSaving]=useState(false);
  async function load(){const[p,profiles,bom,issues]=await Promise.all([supabase.from("products").select("id,code,name,category,status,owner").order("code"),supabase.from("product_strategic_profiles").select("*"),supabase.from("product_structure_items").select("id,product_id,material_code,description,quantity"),supabase.from("product_issues").select("id,product_id,priority,due_date").is("resolved_at",null)]);if(profiles.error)setMessage("Execute o SQL atualizado para ativar a base de inteligência NPI.");setDb({products:p.data??[],profiles:profiles.data??[],bom:bom.data??[],issues:issues.data??[]});}
  useEffect(()=>{load();},[]);
  const radar=useMemo(()=>db.products.map(product=>{const profile=db.profiles.find(x=>x.product_id===product.id);const bom=db.bom.filter(x=>x.product_id===product.id);const issues=db.issues.filter(x=>x.product_id===product.id);const margin=profile?.sale_price>0?(Number(profile.sale_price)-Number(profile.unit_cost))/Number(profile.sale_price)*100:0;let score=profile?25:0;score+=Math.min(Number(profile?.annual_sales||0)/10,20)+(bom.length?15:0)+(profile?.application?10:0)+(profile?.competitor_name?8:0)+(profile&&!profile.single_source?8:-8)+Math.min(Math.max(margin,0)/3,15)-Math.min(issues.length*3,12);return{product,profile,bom,issues,margin,score:Math.max(0,Math.min(100,Math.round(score)))}}).sort((a,b)=>b.score-a.score),[db]);
  const recommendations=useMemo(()=>{const list=[];radar.forEach(x=>{const p=x.profile;if(!p){list.push({level:"info",product:x.product,title:"Completar inteligência do produto",text:"Faltam dados comerciais, técnicos e de suprimentos para uma decisão segura."});return}if(p.single_source)list.push({level:"danger",product:x.product,title:"Reduzir dependência",text:`Fonte única${p.supplier_name?` em ${p.supplier_name}`:""}. Homologue uma alternativa.`});if(Number(p.minimum_stock)>0&&Number(p.stock_quantity)<Number(p.minimum_stock))list.push({level:"warning",product:x.product,title:"Risco de ruptura",text:`Estoque ${p.stock_quantity}; mínimo ${p.minimum_stock}.`});if(x.margin>0&&x.margin<25)list.push({level:"warning",product:x.product,title:"Reduzir custo",text:`Margem estimada em ${x.margin.toFixed(1)}%. Revisar BOM, overhead e negociação.`});if(p.supplier_country&&p.supplier_country.toLowerCase()!=="brasil")list.push({level:"info",product:x.product,title:"Avaliar nacionalização",text:`Fornecedor atual em ${p.supplier_country}; procure equivalentes locais.`});if(x.issues.some(i=>i.priority==="critica"))list.push({level:"danger",product:x.product,title:"Prioridade técnica crítica",text:"Resolva a pendência crítica antes de ampliar o produto."})});const shared={};db.bom.forEach(i=>{shared[i.material_code]??=new Set();shared[i.material_code].add(i.product_id)});Object.entries(shared).filter(([,ids])=>ids.size>1).slice(0,4).forEach(([code,ids])=>list.push({level:"success",title:"Componente reaproveitável",text:`${code} aparece em ${ids.size} produtos e pode ser padronizado em novos NPIs.`}));return list.slice(0,12)},[radar,db.bom]);
  function select(value){setSelectedId(value);const p=db.profiles.find(x=>String(x.product_id)===String(value));setForm(p?Object.fromEntries(Object.keys(blank).map(k=>[k,p[k]??blank[k]])):blank)}
  async function save(e){e.preventDefault();setSaving(true);const payload={...form,product_id:Number(selectedId),updated_at:new Date().toISOString(),certification_expiry:form.certification_expiry||null};numeric.forEach(k=>payload[k]=form[k]===""?null:Number(form[k]));const{data,error}=await supabase.from("product_strategic_profiles").upsert(payload,{onConflict:"product_id"}).select("*").single();if(error)setMessage(error.message);else{await supabase.from("product_strategic_history").insert({product_id:Number(selectedId),event_type:"strategic_profile_updated",description:"Ficha estratégica atualizada na central de inteligência NPI.",metadata:{lifecycle_status:data.lifecycle_status,single_source:data.single_source,certification_status:data.certification_status}});setDb(c=>({...c,profiles:[...c.profiles.filter(x=>x.product_id!==Number(selectedId)),data]}));setMessage("Base estratégica atualizada; recomendações recalculadas.")}setSaving(false)}
  const selected=db.products.find(x=>String(x.id)===String(selectedId));const coverage=radar.filter(x=>x.profile).length;const maturity=radar.length?Math.round(radar.reduce((s,x)=>s+x.score,0)/radar.length):0;
  const field=(label,key,type="text")=><label>{label}<input type={type} min={type==="number"?0:undefined} step={type==="number"?".01":undefined} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>;
  return <main className="strategy-page"><section className="strategy-hero"><div><span>Base de decisão PENN</span><h1>Inteligência estratégica para NPI</h1><p>Engenharia, custos, mercado e suprimentos conectados para decidir o que desenvolver, reaproveitar ou corrigir.</p></div><div className="strategy-score"><strong>{maturity}</strong><span>maturidade da base</span></div></section>
  <section className="strategy-kpis"><article><span>Cobertura estratégica</span><strong>{coverage}/{db.products.length}</strong><small>produtos enriquecidos</small></article><article><span>Recomendações</span><strong>{recommendations.length}</strong><small>oportunidades e riscos</small></article><article className="risk"><span>Fonte única</span><strong>{db.profiles.filter(x=>x.single_source).length}</strong><small>dependências mapeadas</small></article><article><span>Componentes</span><strong>{db.bom.length}</strong><small>itens de BOM analisados</small></article></section>{message&&<p className="strategy-message">{message}</p>}
  <section className="strategy-grid"><article className="strategy-panel recommendations"><header><div><span className="panel-kicker">Motor de oportunidades</span><h2>Recomendações explicáveis</h2></div><small>Em tempo real</small></header><div>{recommendations.map((r,i)=><button className={r.level} key={`${r.product?.id||"shared"}-${i}`} onClick={()=>r.product&&onOpenProduct(r.product.id)}><i>{String(i+1).padStart(2,"0")}</i><span><strong>{r.title}</strong>{r.product&&<small>{r.product.code} · {r.product.name}</small>}<p>{r.text}</p></span><b>→</b></button>)}</div></article><article className="strategy-panel ranking"><header><div><span className="panel-kicker">Priorização</span><h2>Radar de produtos</h2></div><small>0–100</small></header><div>{radar.slice(0,10).map(x=><button key={x.product.id} onClick={()=>select(String(x.product.id))}><span><strong>{x.product.code}</strong><small>{x.product.name}</small></span><i><b style={{width:`${x.score}%`}}/></i><em>{x.score}</em></button>)}</div></article></section>
  <section className="strategy-panel strategy-editor"><header><div><span className="panel-kicker">Enriquecimento da base</span><h2>Ficha estratégica do produto</h2></div><select value={selectedId} onChange={e=>select(e.target.value)}><option value="">Selecione um produto</option>{db.products.map(p=><option value={p.id} key={p.id}>{p.code} — {p.name}</option>)}</select></header>{selected?<form onSubmit={save}><label>Aplicações<textarea rows="2" value={form.application} onChange={e=>setForm({...form,application:e.target.value})}/></label><label>Compatibilidades<textarea rows="2" value={form.compatibility} onChange={e=>setForm({...form,compatibility:e.target.value})}/></label>{field("Vendas anuais","annual_sales","number")}{field("Estoque atual","stock_quantity","number")}{field("Estoque mínimo","minimum_stock","number")}{field("Custo unitário","unit_cost","number")}{field("Preço de venda","sale_price","number")}{field("Lead time (dias)","lead_time_days","number")}{field("Fornecedor principal","supplier_name")}{field("País do fornecedor","supplier_country")}<label>Certificação<select value={form.certification_status} onChange={e=>setForm({...form,certification_status:e.target.value})}><option value="not_required">Não necessária</option><option value="pending">Pendente</option><option value="valid">Válida</option><option value="expired">Vencida</option></select></label>{field("Validade da certificação","certification_expiry","date")}{field("Concorrente de referência","competitor_name")}{field("Preço do concorrente","competitor_price","number")}<label>Ciclo de vida<select value={form.lifecycle_status} onChange={e=>setForm({...form,lifecycle_status:e.target.value})}><option value="development">Desenvolvimento</option><option value="active">Ativo</option><option value="phase_out">Phase-out</option><option value="discontinued">Descontinuado</option></select></label><label className="strategy-check"><input type="checkbox" checked={form.single_source} onChange={e=>setForm({...form,single_source:e.target.checked})}/> Dependência de fonte única</label><label className="wide">Riscos e problemas conhecidos<textarea rows="3" value={form.known_risks} onChange={e=>setForm({...form,known_risks:e.target.value})}/></label><label className="wide">Notas estratégicas<textarea rows="3" value={form.strategic_notes} onChange={e=>setForm({...form,strategic_notes:e.target.value})}/></label><footer><span>Margem percentual: <strong>{form.sale_price>0?((form.sale_price-form.unit_cost)/form.sale_price*100).toFixed(1):"0.0"}%</strong></span><button disabled={saving}>{saving?"Salvando...":"Salvar inteligência"}</button></footer></form>:<div className="strategy-empty">Selecione um produto para construir sua base estratégica.</div>}</section></main>
}
