"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabaseClient";

const emptySupplier={name:"",tax_id:"",contact_name:"",email:"",whatsapp:"",phone:"",website:"",country:"Brasil",city:"",rating:"",status:"active",notes:""};
const emptyContact={name:"",role:"",email:"",phone:"",whatsapp:""};
const supplierFields={name:"Nome",tax_id:"CNPJ (Opcional)",contact_name:"Contato principal",email:"E-mail principal",whatsapp:"WhatsApp",phone:"Telefone",website:"Website",country:"País",city:"Cidade",rating:"Avaliação (0 a 5)"};

function SupplierFormFields({form,setForm}){
  return <>{Object.entries(supplierFields).map(([key,label])=><label key={key}>{label}<input required={key==="name"} type={key==="rating"?"number":"text"} min={key==="rating"?0:undefined} max={key==="rating"?5:undefined} step={key==="rating"?"0.1":undefined} value={form[key]??""} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Ativo</option><option value="qualification">Em qualificação</option><option value="blocked">Bloqueado</option><option value="inactive">Inativo</option></select></label><label className="wide">Observações<textarea rows="3" value={form.notes??""} onChange={e=>setForm({...form,notes:e.target.value})}/></label></>;
}

export default function SupplierDashboard(){
  const[suppliers,setSuppliers]=useState([]);const[materials,setMaterials]=useState([]);const[structures,setStructures]=useState([]);const[materialLinks,setMaterialLinks]=useState([]);const[contacts,setContacts]=useState([]);const[materialAttachments,setMaterialAttachments]=useState([]);
  const[selectedId,setSelectedId]=useState(null);const[mainView,setMainView]=useState("suppliers");const[supplierTab,setSupplierTab]=useState("data");const[createForm,setCreateForm]=useState(emptySupplier);const[editForm,setEditForm]=useState(emptySupplier);const[editing,setEditing]=useState(false);const[contactForm,setContactForm]=useState(emptyContact);const[contactDrafts,setContactDrafts]=useState({});const[linkMaterial,setLinkMaterial]=useState("");const[materialDrafts,setMaterialDrafts]=useState({});const[message,setMessage]=useState("");

  async function load(){const[s,m,st,sm,sc,sa]=await Promise.all([supabase.from("suppliers").select("*").order("name"),supabase.from("raw_materials").select("id,code,name").order("code"),supabase.from("product_structure_items").select("id,product_id,material_code,description,quantity"),supabase.from("supplier_materials").select("*"),supabase.from("supplier_contacts").select("*").order("created_at"),supabase.from("supplier_material_attachments").select("*").order("created_at")]);setSuppliers(s.data??[]);setMaterials(m.data??[]);setStructures(st.data??[]);setMaterialLinks(sm.data??[]);setContacts(sc.data??[]);setMaterialAttachments(sa.data??[]);}
  useEffect(()=>{load()},[]);
  const selected=suppliers.find(s=>s.id===selectedId);
  function selectSupplier(id){const supplier=suppliers.find(s=>s.id===id);setSelectedId(id);setEditForm(supplier?{...emptySupplier,...supplier}:emptySupplier);setEditing(false);setSupplierTab("data");setMessage("");}
  function payload(form){return{name:form.name,tax_id:form.tax_id||null,contact_name:form.contact_name||null,email:form.email||null,whatsapp:form.whatsapp||null,phone:form.phone||null,website:form.website||null,country:form.country||null,city:form.city||null,rating:form.rating===""||form.rating==null?null:Number(form.rating),status:form.status,notes:form.notes||null}}
  async function createSupplier(e){e.preventDefault();const{data,error}=await supabase.from("suppliers").insert(payload(createForm)).select("*").single();if(error){setMessage(error.message);return}setSuppliers(c=>[...c,data].sort((a,b)=>a.name.localeCompare(b.name)));setCreateForm(emptySupplier);setMainView("suppliers");setSelectedId(data.id);setEditForm({...emptySupplier,...data});setMessage("Fornecedor cadastrado com sucesso.");}
  async function updateSupplier(e){e.preventDefault();const{data,error}=await supabase.from("suppliers").update({...payload(editForm),updated_at:new Date().toISOString()}).eq("id",selectedId).select("*").single();if(error){setMessage(error.message);return}setSuppliers(c=>c.map(s=>s.id===data.id?data:s).sort((a,b)=>a.name.localeCompare(b.name)));setEditForm({...emptySupplier,...data});setEditing(false);setMessage("Dados do fornecedor atualizados.");}
  async function addContact(e){e.preventDefault();const{data,error}=await supabase.from("supplier_contacts").insert({...contactForm,supplier_id:selectedId}).select("*").single();if(error){setMessage(error.message);return}setContacts(c=>[...c,data]);setContactForm(emptyContact);}
  function changeContact(contact,key,value){setContactDrafts(c=>({...c,[contact.id]:{...(c[contact.id]||contact),[key]:value}}))}
  async function updateContact(contact){const draft=contactDrafts[contact.id]||contact;const values={name:draft.name,role:draft.role||null,email:draft.email||null,phone:draft.phone||null,whatsapp:draft.whatsapp||null};const{data,error}=await supabase.from("supplier_contacts").update(values).eq("id",contact.id).select("*").single();if(error){setMessage(error.message);return}setContacts(c=>c.map(x=>x.id===contact.id?data:x));setContactDrafts(c=>{const next={...c};delete next[contact.id];return next});setMessage("Contato atualizado.");}
  async function removeContact(id){if(!window.confirm("Excluir este contato adicional?"))return;const{error}=await supabase.from("supplier_contacts").delete().eq("id",id);if(error){setMessage(error.message);return}setContacts(c=>c.filter(x=>x.id!==id));}
  async function addMaterial(){if(!selectedId||!linkMaterial)return;const row={supplier_id:selectedId,raw_material_id:Number(linkMaterial),currency:"BRL"};const{data,error}=await supabase.from("supplier_materials").upsert(row).select("*").single();if(error){setMessage(error.message);return}setMaterialLinks(c=>[...c.filter(x=>!(x.supplier_id===selectedId&&x.raw_material_id===row.raw_material_id)),data]);setLinkMaterial("");}
  function materialValue(link,key){return materialDrafts[link.raw_material_id]?.[key]??link[key]??""}
  function changeMaterial(link,key,value){setMaterialDrafts(c=>({...c,[link.raw_material_id]:{...(c[link.raw_material_id]||{}),[key]:value}}))}
  async function saveMaterial(link){const draft=materialDrafts[link.raw_material_id]||{};const lastPrice=draft.last_price??link.last_price;const minimumOrder=draft.minimum_order??link.minimum_order;const values={supplier_part_number:draft.supplier_part_number??link.supplier_part_number??null,last_price:lastPrice===""||lastPrice==null?null:Number(lastPrice),currency:draft.currency??link.currency??"BRL",minimum_order:minimumOrder===""||minimumOrder==null?null:Number(minimumOrder)};const{data,error}=await supabase.from("supplier_materials").update(values).eq("supplier_id",selectedId).eq("raw_material_id",link.raw_material_id).select("*").single();if(error){setMessage(error.message);return}setMaterialLinks(c=>c.map(x=>x.supplier_id===selectedId&&x.raw_material_id===link.raw_material_id?data:x));setMaterialDrafts(c=>{const next={...c};delete next[link.raw_material_id];return next});setMessage("Matéria-prima atualizada.");}
  async function removeMaterial(rawMaterialId){if(!window.confirm("Remover esta matéria-prima do fornecedor?"))return;const files=materialAttachments.filter(x=>x.supplier_id===selectedId&&x.raw_material_id===rawMaterialId);const{error}=await supabase.from("supplier_materials").delete().eq("supplier_id",selectedId).eq("raw_material_id",rawMaterialId);if(error){setMessage(error.message);return}if(files.length)await supabase.storage.from("product-files").remove(files.map(x=>x.storage_path));setMaterialLinks(c=>c.filter(x=>!(x.supplier_id===selectedId&&x.raw_material_id===rawMaterialId)));setMaterialAttachments(c=>c.filter(x=>!(x.supplier_id===selectedId&&x.raw_material_id===rawMaterialId)));}
  async function uploadMaterialAttachment(link,file){if(!file)return;const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const storagePath=`supplier-materials/${selectedId}/${link.raw_material_id}/${Date.now()}-${safeName}`;const{error:uploadError}=await supabase.storage.from("product-files").upload(storagePath,file);if(uploadError){setMessage(uploadError.message);return}const{data:urlData}=supabase.storage.from("product-files").getPublicUrl(storagePath);const{data,error}=await supabase.from("supplier_material_attachments").insert({supplier_id:selectedId,raw_material_id:link.raw_material_id,name:file.name,storage_path:storagePath,public_url:urlData.publicUrl}).select("*").single();if(error){await supabase.storage.from("product-files").remove([storagePath]);setMessage(error.message);return}setMaterialAttachments(c=>[...c,data]);setMessage("Anexo adicionado à matéria-prima.");}
  async function removeMaterialAttachment(item){if(!window.confirm("Excluir este anexo?"))return;const{error}=await supabase.from("supplier_material_attachments").delete().eq("id",item.id);if(error){setMessage(error.message);return}await supabase.storage.from("product-files").remove([item.storage_path]);setMaterialAttachments(c=>c.filter(x=>x.id!==item.id));}
  async function deleteSupplier(){if(!selected)return;const verification=window.prompt(`Para excluir definitivamente, digite o nome do fornecedor:\n${selected.name}`);if(verification===null)return;if(verification.trim()!==selected.name){setMessage("Verificação cancelada: o nome informado não corresponde ao fornecedor.");return}const files=materialAttachments.filter(x=>x.supplier_id===selected.id);const{error}=await supabase.from("suppliers").delete().eq("id",selected.id);if(error){setMessage(error.message);return}if(files.length)await supabase.storage.from("product-files").remove(files.map(x=>x.storage_path));setSuppliers(c=>c.filter(x=>x.id!==selected.id));setMaterialLinks(c=>c.filter(x=>x.supplier_id!==selected.id));setContacts(c=>c.filter(x=>x.supplier_id!==selected.id));setMaterialAttachments(c=>c.filter(x=>x.supplier_id!==selected.id));setSelectedId(null);setMessage("Fornecedor excluído com sucesso.");}

  const selectedLinks=materialLinks.filter(x=>x.supplier_id===selectedId);const selectedContacts=contacts.filter(x=>x.supplier_id===selectedId);
  return <main className="supplier-page">
    <section className="supplier-hero"><div><span>Supplier Relationship Management</span><h1>Fornecedores</h1><p>Gerencie sua rede, contatos e matérias-primas fornecidas em um único espaço.</p></div><strong>{suppliers.length}<small> fornecedores cadastrados</small></strong></section>
    <nav className="supplier-main-tabs"><button className={mainView==="suppliers"?"active":""} onClick={()=>setMainView("suppliers")}>Rede de fornecedores <b>{suppliers.length}</b></button><button className={mainView==="new"?"active":""} onClick={()=>setMainView("new")}>+ Novo fornecedor</button></nav>
    {message&&<p className="supplier-message">{message}</p>}
    {mainView==="new"?<form className="supplier-form supplier-create-panel" onSubmit={createSupplier}><header><span>Cadastro SRM</span><h2>Novo fornecedor</h2><p>Registre os dados principais. Contatos adicionais e matérias-primas poderão ser incluídos depois.</p></header><SupplierFormFields form={createForm} setForm={setCreateForm}/><button>Cadastrar fornecedor</button></form>:<section className="supplier-layout">
      <aside><span className="supplier-list-kicker">Sua rede</span><h2>Fornecedores cadastrados</h2>{suppliers.map(s=><button className={selectedId===s.id?"active":""} onClick={()=>selectSupplier(s.id)} key={s.id}><strong>{s.name}</strong><small>{s.city||s.country||"Local não informado"} · {s.status}</small></button>)}</aside>
      <section className="supplier-detail">{selected?<><header><div><span>Fornecedor selecionado</span><h2>{selected.name}</h2></div><div className="supplier-header-actions"><span className={`supplier-status ${selected.status}`}>{selected.status}</span><button className="supplier-delete" onClick={deleteSupplier}>Excluir fornecedor</button></div></header>
        <nav className="supplier-detail-tabs"><button className={supplierTab==="data"?"active":""} onClick={()=>setSupplierTab("data")}>Dados e contatos</button><button className={supplierTab==="materials"?"active":""} onClick={()=>setSupplierTab("materials")}>Matérias-primas <b>{selectedLinks.length}</b></button></nav>
        {supplierTab==="data"&&<div className="supplier-data-tab">{editing?<form className="supplier-edit-form" onSubmit={updateSupplier}><SupplierFormFields form={editForm} setForm={setEditForm}/><footer><button type="button" onClick={()=>setEditing(false)}>Cancelar</button><button>Salvar alterações</button></footer></form>:<><div className="supplier-contact-grid"><div><small>Contato principal</small><strong>{selected.contact_name||"Não informado"}</strong></div><div><small>E-mail</small><strong>{selected.email||"Não informado"}</strong></div><div><small>WhatsApp</small><strong>{selected.whatsapp||"Não informado"}</strong></div><div><small>Telefone</small><strong>{selected.phone||"Não informado"}</strong></div><div><small>Localização</small><strong>{[selected.city,selected.country].filter(Boolean).join(" · ")||"Não informada"}</strong></div><div><small>Avaliação</small><strong>{selected.rating?`${selected.rating}/5`:"Sem avaliação"}</strong></div></div><button className="supplier-edit-trigger" onClick={()=>{setEditForm({...emptySupplier,...selected});setEditing(true)}}>Editar dados do fornecedor</button></>}
          <section className="supplier-contacts"><header><div><span>Equipe de contato</span><h3>Contatos adicionais</h3></div></header><div className="supplier-contact-list">{selectedContacts.map(contact=>{const draft=contactDrafts[contact.id]||contact;return <article className="editable" key={contact.id}><div className="supplier-contact-fields"><input aria-label="Nome do contato" value={draft.name||""} onChange={e=>changeContact(contact,"name",e.target.value)}/><input aria-label="Cargo ou área" placeholder="Cargo / área" value={draft.role||""} onChange={e=>changeContact(contact,"role",e.target.value)}/><input type="email" aria-label="E-mail do contato" placeholder="E-mail" value={draft.email||""} onChange={e=>changeContact(contact,"email",e.target.value)}/><input aria-label="Telefone do contato" placeholder="Telefone" value={draft.phone||""} onChange={e=>changeContact(contact,"phone",e.target.value)}/><input aria-label="WhatsApp do contato" placeholder="WhatsApp" value={draft.whatsapp||""} onChange={e=>changeContact(contact,"whatsapp",e.target.value)}/></div><div className="supplier-contact-actions"><button onClick={()=>removeContact(contact.id)}>Excluir</button><button onClick={()=>updateContact(contact)}>Salvar</button></div></article>})}{!selectedContacts.length&&<p>Nenhum contato adicional cadastrado.</p>}</div><form onSubmit={addContact}><input required placeholder="Nome" value={contactForm.name} onChange={e=>setContactForm({...contactForm,name:e.target.value})}/><input placeholder="Cargo / área" value={contactForm.role} onChange={e=>setContactForm({...contactForm,role:e.target.value})}/><input type="email" placeholder="E-mail" value={contactForm.email} onChange={e=>setContactForm({...contactForm,email:e.target.value})}/><input placeholder="Telefone" value={contactForm.phone} onChange={e=>setContactForm({...contactForm,phone:e.target.value})}/><input placeholder="WhatsApp" value={contactForm.whatsapp} onChange={e=>setContactForm({...contactForm,whatsapp:e.target.value})}/><button>Adicionar contato</button></form></section></div>}
        {supplierTab==="materials"&&<section className="supplier-materials-tab"><header><div><span>Portfólio do fornecedor</span><h3>Matérias-primas fornecidas</h3></div><div className="relation-add"><select value={linkMaterial} onChange={e=>setLinkMaterial(e.target.value)}><option value="">Selecionar matéria-prima</option>{materials.filter(m=>!selectedLinks.some(link=>link.raw_material_id===m.id)).map(m=><option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select><button onClick={addMaterial}>Adicionar</button></div></header><div className="supplier-material-list">{selectedLinks.map(link=>{const material=materials.find(x=>x.id===link.raw_material_id);const uses=structures.filter(st=>st.material_code===material?.code);const attachments=materialAttachments.filter(item=>item.supplier_id===selectedId&&item.raw_material_id===link.raw_material_id);return <article key={link.raw_material_id}><header><div><strong>{material?.code}</strong><h4>{material?.name}</h4></div><span>{new Set(uses.map(u=>u.product_id)).size} estrutura(s)</span></header><div><label>P/N do fornecedor<input value={materialValue(link,"supplier_part_number")} onChange={e=>changeMaterial(link,"supplier_part_number",e.target.value)}/></label><label>Último preço<input type="number" min="0" step="0.01" value={materialValue(link,"last_price")} onChange={e=>changeMaterial(link,"last_price",e.target.value)}/></label><label>Moeda<select value={materialValue(link,"currency")||"BRL"} onChange={e=>changeMaterial(link,"currency",e.target.value)}><option>BRL</option><option>USD</option></select></label><label>Pedido mínimo<input type="number" min="0" step="0.01" value={materialValue(link,"minimum_order")} onChange={e=>changeMaterial(link,"minimum_order",e.target.value)}/></label></div><section className="supplier-material-attachments"><label>Adicionar anexo<input type="file" onChange={e=>{uploadMaterialAttachment(link,e.target.files?.[0]);e.target.value=""}}/></label><div>{attachments.map(item=><span key={item.id}><a href={item.public_url} target="_blank" rel="noreferrer">{item.name}</a><button onClick={()=>removeMaterialAttachment(item)}>×</button></span>)}{!attachments.length&&<small>Nenhum anexo</small>}</div></section><footer><button onClick={()=>removeMaterial(link.raw_material_id)}>Excluir item</button><button onClick={()=>saveMaterial(link)}>Salvar item</button></footer></article>})}{!selectedLinks.length&&<div className="supplier-empty"><strong>Nenhuma matéria-prima vinculada</strong><span>Use o seletor acima para montar o portfólio deste fornecedor.</span></div>}</div></section>}
      </>:<div className="supplier-empty"><strong>Selecione um fornecedor</strong><span>Os dados, contatos e matérias-primas serão exibidos aqui.</span></div>}</section>
    </section>}
  </main>;
}
